name: ${project.name}
version: ${project.version}
author: Tobi
main: net.coalcube.bansystem.spigot.BanSystemSpigot
commands:
  ban:
  unban:
  history:
  deletehistory:
  unmute:
  kick:
  check:
  bansystem:
  bansys:
